### ISSUE TITLE
Use .eu instead of .nl domain

### ISSUE THREAD

**Issue by PerryVanKuppeveld** [janssenr/PostcodeNlApiRestClient#1]
Hi,

As far as I can see in the code the depricated .nl domain is used:
https://api.postcode.nl/documentation/json-rest/v1/Address/viewByPostcode

A newer version on the .eu domain is also available:
https://api.postcode.nl/documentation/nl/v1/Address/viewByPostcode

**Comment by janssenr** [comment]
I changed the code so "addresses/postcode" is used within the DoRestCall function.
So the new EndPoint "https://api.postcode.eu/nl/v1" can also be used.
You can pass it with the constructor.
But I don't see any differences between the old one and the new one.
