### ISSUE TITLE
upon trying to make successfull Httpwebrequest  to https://api.postcode.eu/nl/v1/addresses/postcode ends up in authentication failed error.

### ISSUE THREAD

**Issue by vidhuamit0606** [janssenr/PostcodeNlApiRestClient#4]
Hi @janssenr , could you please guide me understanding in why I am failing to make an Httpwebrequest  to PostCode API
[
![Error_postcodenl_API](https://user-images.githubusercontent.com/9607899/109390116-b31a3980-7935-11eb-84bb-65e5443af7dc.png)
![Error_postcodenl_API2](https://user-images.githubusercontent.com/9607899/109390117-b4e3fd00-7935-11eb-9ad1-8c993c7a79d9.png)

]

also please refer to the screen shots I have made available here . Anticipating for a quick Reply.

**Comment by janssenr** [comment]
I see you have changed the original code?
Why did you change the original code?
The original code is working (on my computer) ;)

**Comment by janssenr** [comment]
What error do you get?
Because I changed my code to yours, and that's also working.
Or did you change more code?

I cannot see which value you are using for AuthenticationLevel (None, MutualAuthRequired or MutualAuthRequested).
But all three are working on my side.

**Comment by janssenr** [comment]
Did you enter the appKey and AppSecret in the Web.Config?

**Comment by vidhuamit0606** [comment]
Hi @janssenr , I did , request to connect with for few minutes for a quick fix at Teams call.

**Comment by janssenr** [comment]
@vidhuamit0606 do you want a call with me?

**Comment by vidhuamit0606** [comment]
Hi @janssenr , please take a look at the error I got 
![image](https://user-images.githubusercontent.com/9607899/109516634-67e75e80-7ace-11eb-9aba-85d543a43dc6.png)

Actually , I am able to get sucessfull response from Postman tool as
![image](https://user-images.githubusercontent.com/9607899/109516769-949b7600-7ace-11eb-9d82-12a7073e7b99.png)


But the same is challenged in >net Application code

**Comment by janssenr** [comment]
What is the error? I don't see the error.

**Comment by vidhuamit0606** [comment]
Hi @janssenr , please take look at the error 
![image](https://user-images.githubusercontent.com/9607899/109517318-21463400-7acf-11eb-97ad-e2f6c84ad970.png)

earlier scrshot was to make you aware of request structure (headers)

**Comment by vidhuamit0606** [comment]
Hi @janssenr , can we quickly using TeamViewer

**Comment by janssenr** [comment]
I'm in a meeting at the moment. After this meeting we can.
Can you sent me TeamViewer details?

**Comment by janssenr** [comment]
Meeting is over. So you can sent me TeamViewer details.

**Comment by vidhuamit0606** [comment]
Hi @janssen, please connect using credentials as
771 456 777/2wm23s

**Comment by vidhuamit0606** [comment]
please share your ID as well to connect

**Comment by vidhuamit0606** [comment]
Hi @janssenr are you able to take control now

**Comment by janssenr** [comment]
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Can you try to add this line of code to DoRestCall (before var req)

**Comment by janssenr** [comment]
No response received
