### ISSUE TITLE
The object (response) is closed too fast and can not be used after closing

### ISSUE THREAD

**Issue by ronaldbalk** [janssenr/PostcodeNlApiRestClient#7]
namespace PostcodeNlApi
    public class PostcodeNlApiRestClient
        protected string DoRestCall(string url)

Response is closed her:
 response.Close();

And two lines further you ask for the StatusCode of the response:
                    var exception = JsonHelper.Deserialize<PostcodeNlException>(responseValue);

                    switch (response.StatusCode)

**Comment by janssenr** [comment]
The stream is closed.
But the response still has the StatusCode set.

Do you have a example which is not working?

**Comment by ronaldbalk** [comment]
Thanks for the fast response.

When the combination PC and number is correct this routine is not reached.

But when the combination is not valid or the credentials for the api are not correct you will receive the following exception when accesing: switch (response.StatusCode):

{"Cannot access a disposed object.\r\nObject name: 'System.Net.HttpWebResponse'."}

 

Greetings

Ronald 

 

Van: Rob Janssen ***@***.***> 
Verzonden: dinsdag 1 oktober 2024 20:16
Aan: janssenr/PostcodeNlApiRestClient ***@***.***>
CC: ronaldbalk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [janssenr/PostcodeNlApiRestClient] The object (response) is closed too fast and can not be used after closing (Issue #7)

 

The stream is closed.
But the response still has the StatusCode set.

Do you have a example which is not working?

**Comment by janssenr** [comment]
I created a local variable for responseStatusCode

**Comment by ronaldbalk** [comment]
Good solution. Thanks

Ronald 

 

Van: Rob Janssen ***@***.***> 
Verzonden: vrijdag 4 oktober 2024 15:25
Aan: janssenr/PostcodeNlApiRestClient ***@***.***>
CC: ronaldbalk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [janssenr/PostcodeNlApiRestClient] The object (response) is closed too fast and can not be used after closing (Issue #7)

 

I created a local variable for responseStatusCode
